"""Add meeting_link column to shortlisted_candidate

Revision ID: e2da8f0c0d03
Revises: 
Create Date: 2025-04-04 18:20:20.266681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2da8f0c0d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shortlisted_candidate', sa.Column('meeting_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shortlisted_candidate', 'meeting_link')
    # ### end Alembic commands ###
